const { test, expect } = require('@playwright/test');
const MAPPER = "function buildDomTextOffsetMap(root) {\n  const invisible = /[\\u061C\\u200B-\\u200F\\u202A-\\u202E\\u2060\\u2066-\\u2069\\uFEFF]/;\n  const space = /[\\u00A0\\u2007\\u202F\\s]/;\n  const events = [];\n  const walker = document.createTreeWalker(root, NodeFilter.SHOW_ALL);\n  let node;\n  while ((node = walker.nextNode())) {\n    if (node.nodeType === Node.TEXT_NODE) events.push({kind:'text',node,value:node.nodeValue||''});\n    else if (node.nodeType === Node.ELEMENT_NODE && node.nodeName.toUpperCase() === 'BR') events.push({kind:'br',node});\n  }\n  const entries = []; let pending = null;\n  const point = (node, offset) => ({node, offset});\n  const brPoint = (br, after) => { const p=br.parentNode; const i=Array.prototype.indexOf.call(p.childNodes,br); return point(p,i+(after?1:0)); };\n  const add = (ch,start,end) => entries.push({ch,start,end});\n  const flush = () => { if (pending) { add(' ',pending.start,pending.end); pending=null; } };\n  for (const part of events) {\n    if (part.kind === 'br') { if (!pending) pending={start:brPoint(part.node,false),end:brPoint(part.node,true)}; else pending.end=brPoint(part.node,true); continue; }\n    for (let i=0;i<part.value.length;i++) { const ch=part.value[i]; const s=point(part.node,i), e=point(part.node,i+1);\n      if (invisible.test(ch)) continue;\n      if (space.test(ch)) { if (!pending) pending={start:s,end:e}; else pending.end=e; continue; }\n      flush(); add(ch,s,e);\n    }\n  }\n  flush();\n  let first=0,last=entries.length; while(first<last&&entries[first].ch===' ')first++; while(last>first&&entries[last-1].ch===' ')last--;\n  const kept=entries.slice(first,last); const text=kept.map(x=>x.ch).join('');\n  const boundaries=kept.length?[kept[0].start,...kept.slice(0,-1).map(x=>x.end),kept[kept.length-1].end]:[point(root,0)];\n  function makeRange(start,end){ const r=document.createRange(); const s=boundaries[Math.max(0,Math.min(start,boundaries.length-1))]; const e=boundaries[Math.max(0,Math.min(end,boundaries.length-1))]; r.setStart(s.node,s.offset); r.setEnd(e.node,e.offset); return r; }\n  return {text,boundaries,makeRange};\n}";
async function load(page, html) { await page.setContent(html); await page.addScriptTag({content:MAPPER}); }
test.describe('research: generic DOM text/offset bridge', () => {
  test('single text node and DOM range', async ({page}) => { await load(page,'<div id="scope">John 3:16</div>'); const r=await page.evaluate(()=>{const m=buildDomTextOffsetMap(document.querySelector('#scope')); const i=m.text.indexOf('John 3:16'); return {text:m.text,selected:m.makeRange(i,i+9).toString()};}); expect(r).toEqual({text:'John 3:16',selected:'John 3:16'}); });
  test('nested and sibling text nodes', async ({page}) => { await load(page,'<div id="scope"><strong>John</strong><span> 3:</span><em>16</em></div>'); const r=await page.evaluate(()=>{const m=buildDomTextOffsetMap(document.querySelector('#scope')); const i=m.text.indexOf('John 3:16'); return {text:m.text,selected:m.makeRange(i,i+9).toString()};}); expect(r).toEqual({text:'John 3:16',selected:'John 3:16'}); });
  test('normalization of NBSP bidi repeated whitespace and trim', async ({page}) => { await load(page,'<div id="scope"> \u00a0<span>Jo\u200hn</span> \n 3:16 \u00a0</div>'); expect(await page.evaluate(()=>buildDomTextOffsetMap(document.querySelector('#scope')).text)).toBe('John 3:16'); });
  test('BR becomes logical whitespace with recoverable DOM range', async ({page}) => { await load(page,'<div id="scope">John<br>3:16</div>'); const r=await page.evaluate(()=>{const m=buildDomTextOffsetMap(document.querySelector('#scope')); const i=m.text.indexOf('John 3:16'); return {text:m.text,selected:m.makeRange(i,i+9).toString()};}); expect(r.text).toBe('John 3:16'); expect(r.selected.replace(/\s+/g,' ')).toBe('John 3:16'); });
  test('duplicate refs remain positionally addressable', async ({page}) => { await load(page,'<div id="scope"><p>John 3:16</p><p>John 3:16</p></div>'); const r=await page.evaluate(()=>{const m=buildDomTextOffsetMap(document.querySelector('#scope').firstElementChild); return {text:m.text,selected:m.makeRange(0,m.text.length).toString()};}); expect(r).toEqual({text:'John 3:16',selected:'John 3:16'}); });
  test('caller scope prevents unrelated references from entering context', async ({page}) => { await page.setContent('<div>Matthew 18</div><div id="scope">Luke 17</div>'); await page.addScriptTag({content:MAPPER}); expect(await page.evaluate(()=>buildDomTextOffsetMap(document.querySelector('#scope')).text)).toBe('Luke 17'); });
  test('numbered books are just text to the mapper', async ({page}) => { await load(page,'<div id="scope"><span>1 </span><strong>Thessalonians 5:21</strong></div>'); expect(await page.evaluate(()=>buildDomTextOffsetMap(document.querySelector('#scope')).text)).toBe('1 Thessalonians 5:21'); });
});