const { test, expect } = require('@playwright/test');
const MAPPER = "function buildDomTextOffsetMap(root) {\n  const invisible = /[\\u061C\\u200B-\\u200F\\u202A-\\u202E\\u2060\\u2066-\\u2069\\uFEFF]/;\n  const space = /[\\u00A0\\u2007\\u202F\\s]/;\n  const events = [];\n  const walker = document.createTreeWalker(root, NodeFilter.SHOW_ALL);\n  let node;\n  while ((node = walker.nextNode())) {\n    if (node.nodeType === Node.TEXT_NODE) events.push({kind:'text',node,value:node.nodeValue||''});\n    else if (node.nodeType === Node.ELEMENT_NODE && node.nodeName.toUpperCase()==='BR') events.push({kind:'br',node});\n  }\n  const entries=[]; let pending=null;\n  const point=(n,o)=>({node:n,offset:o});\n  const brPoint=(br,after)=>{const p=br.parentNode,i=Array.prototype.indexOf.call(p.childNodes,br);return point(p,i+(after?1:0));};\n  const add=(ch,start,end)=>entries.push({ch,start,end});\n  const flush=()=>{if(pending){add(' ',pending.start,pending.end);pending=null;}};\n  for(const part of events){\n    if(part.kind==='br'){if(!pending)pending={start:brPoint(part.node,false),end:brPoint(part.node,true)};else pending.end=brPoint(part.node,true);continue;}\n    for(let i=0;i<part.value.length;i++){\n      const ch=part.value[i],start=point(part.node,i),end=point(part.node,i+1);\n      if(invisible.test(ch))continue;\n      if(space.test(ch)){if(!pending)pending={start,end};else pending.end=end;continue;}\n      flush();add(ch,start,end);\n    }\n  }\n  flush();\n  let first=0,last=entries.length;\n  while(first<last&&entries[first].ch===' ')first++;\n  while(last>first&&entries[last-1].ch===' ')last--;\n  const kept=entries.slice(first,last),text=kept.map(x=>x.ch).join('');\n  const boundaries=kept.length?[kept[0].start,...kept.slice(0,-1).map(x=>x.end),kept[kept.length-1].end]:[point(root,0)];\n  function makeRange(start,end){const r=document.createRange(),s=boundaries[Math.max(0,Math.min(start,boundaries.length-1))],e=boundaries[Math.max(0,Math.min(end,boundaries.length-1))];r.setStart(s.node,s.offset);r.setEnd(e.node,e.offset);return r;}\n  return {text,boundaries,makeRange};\n}\n";
async function map(page, html, selector='#scope'){
  await page.setContent(html);
  await page.addScriptTag({content:MAPPER});
  return page.evaluate(sel=>{const m=buildDomTextOffsetMap(document.querySelector(sel));return {text:m.text,full:m.makeRange(0,m.text.length).toString()};},selector);
}
test.describe('research: generic DOM text/offset bridge',()=>{
  test('single text node',async({page})=>{expect(await map(page,'<div id="scope">John 3:16</div>')).toEqual({text:'John 3:16',full:'John 3:16'});});
  test('nested and sibling text nodes',async({page})=>{expect(await map(page,'<div id="scope"><strong>John</strong><span> 3:</span><em>16</em></div>')).toEqual({text:'John 3:16',full:'John 3:16'});});
  test('normalizes NBSP, bidi marks, repeated whitespace and trim',async({page})=>{expect(await map(page,'<div id="scope"> \u00a0<span>Jo\u200hn</span> \n 3:16 \u00a0</div>')).toEqual({text:'John 3:16',full:'John 3:16'});});
  test('maps BR as logical whitespace while retaining a DOM range',async({page})=>{const r=await map(page,'<div id="scope">John<br>3:16</div>');expect(r.text).toBe('John 3:16');expect(r.full.replace(/\s+/g,' ')).toBe('John 3:16');});
  test('isolates caller-selected scope',async({page})=>{expect(await map(page,'<div>Matthew 18</div><div id="scope">Luke 17</div>')).toEqual({text:'Luke 17',full:'Luke 17'});});
  test('keeps numbered books as ordinary text',async({page})=>{expect(await map(page,'<div id="scope"><span>1 </span><strong>Thessalonians 5:21</strong></div>')).toEqual({text:'1 Thessalonians 5:21',full:'1 Thessalonians 5:21'});});
  test('reconstructs only requested logical subrange',async({page})=>{await page.setContent('<div id="scope"><strong>John</strong><span> 3:</span><em>16</em></div>');await page.addScriptTag({content:MAPPER});const selected=await page.evaluate(()=>{const m=buildDomTextOffsetMap(document.querySelector('#scope')),start=m.text.indexOf('3:16');return m.makeRange(start,start+4).toString();});expect(selected).toBe('3:16');});
});